version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Building Docker image...
      - cd services/user-service
      - docker build -t $ECR_REGISTRY/ecommerce/user-service:$IMAGE_TAG .
      - docker tag $ECR_REGISTRY/ecommerce/user-service:$IMAGE_TAG $ECR_REGISTRY/ecommerce/user-service:latest
  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $ECR_REGISTRY/ecommerce/user-service:$IMAGE_TAG
      - docker push $ECR_REGISTRY/ecommerce/user-service:latest
      - printf '[{"name":"product-service","imageUri":"%s"}]' $ECR_REGISTRY/ecommerce/user-service:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json